
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model Operadores
 * 
 */
export type Operadores = Prisma.OperadoresModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Usuarios
 * 
 */
export type Usuarios = Prisma.UsuariosModel
/**
 * Model Verification
 * 
 */
export type Verification = Prisma.VerificationModel
/**
 * Model Emprestimo
 * 
 */
export type Emprestimo = Prisma.EmprestimoModel
/**
 * Model Chave
 * 
 */
export type Chave = Prisma.ChaveModel
/**
 * Model Chaves_Usuarios
 * 
 */
export type Chaves_Usuarios = Prisma.Chaves_UsuariosModel
/**
 * Model Ambiente
 * 
 */
export type Ambiente = Prisma.AmbienteModel
/**
 * Model Armario
 * 
 */
export type Armario = Prisma.ArmarioModel
