
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.js"
import type * as Prisma from "./internal/prismaNamespace.js"


export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type DateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type DateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type EnumStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.Status | Prisma.EnumStatusFieldRefInput<$PrismaModel>
  in?: $Enums.Status[] | Prisma.ListEnumStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.Status[] | Prisma.ListEnumStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumStatusFilter<$PrismaModel> | $Enums.Status
}

export type EnumTipoEmprestimoFilter<$PrismaModel = never> = {
  equals?: $Enums.TipoEmprestimo | Prisma.EnumTipoEmprestimoFieldRefInput<$PrismaModel>
  in?: $Enums.TipoEmprestimo[] | Prisma.ListEnumTipoEmprestimoFieldRefInput<$PrismaModel>
  notIn?: $Enums.TipoEmprestimo[] | Prisma.ListEnumTipoEmprestimoFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTipoEmprestimoFilter<$PrismaModel> | $Enums.TipoEmprestimo
}

export type EnumStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Status | Prisma.EnumStatusFieldRefInput<$PrismaModel>
  in?: $Enums.Status[] | Prisma.ListEnumStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.Status[] | Prisma.ListEnumStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumStatusWithAggregatesFilter<$PrismaModel> | $Enums.Status
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumStatusFilter<$PrismaModel>
}

export type EnumTipoEmprestimoWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TipoEmprestimo | Prisma.EnumTipoEmprestimoFieldRefInput<$PrismaModel>
  in?: $Enums.TipoEmprestimo[] | Prisma.ListEnumTipoEmprestimoFieldRefInput<$PrismaModel>
  notIn?: $Enums.TipoEmprestimo[] | Prisma.ListEnumTipoEmprestimoFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTipoEmprestimoWithAggregatesFilter<$PrismaModel> | $Enums.TipoEmprestimo
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTipoEmprestimoFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTipoEmprestimoFilter<$PrismaModel>
}

export type EnumTipoChaveFilter<$PrismaModel = never> = {
  equals?: $Enums.TipoChave | Prisma.EnumTipoChaveFieldRefInput<$PrismaModel>
  in?: $Enums.TipoChave[] | Prisma.ListEnumTipoChaveFieldRefInput<$PrismaModel>
  notIn?: $Enums.TipoChave[] | Prisma.ListEnumTipoChaveFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTipoChaveFilter<$PrismaModel> | $Enums.TipoChave
}

export type EnumTipoChaveWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TipoChave | Prisma.EnumTipoChaveFieldRefInput<$PrismaModel>
  in?: $Enums.TipoChave[] | Prisma.ListEnumTipoChaveFieldRefInput<$PrismaModel>
  notIn?: $Enums.TipoChave[] | Prisma.ListEnumTipoChaveFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTipoChaveWithAggregatesFilter<$PrismaModel> | $Enums.TipoChave
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTipoChaveFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTipoChaveFilter<$PrismaModel>
}

export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type EnumLocalizacaoFilter<$PrismaModel = never> = {
  equals?: $Enums.Localizacao | Prisma.EnumLocalizacaoFieldRefInput<$PrismaModel>
  in?: $Enums.Localizacao[] | Prisma.ListEnumLocalizacaoFieldRefInput<$PrismaModel>
  notIn?: $Enums.Localizacao[] | Prisma.ListEnumLocalizacaoFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLocalizacaoFilter<$PrismaModel> | $Enums.Localizacao
}

export type EnumTipoAmbienteFilter<$PrismaModel = never> = {
  equals?: $Enums.TipoAmbiente | Prisma.EnumTipoAmbienteFieldRefInput<$PrismaModel>
  in?: $Enums.TipoAmbiente[] | Prisma.ListEnumTipoAmbienteFieldRefInput<$PrismaModel>
  notIn?: $Enums.TipoAmbiente[] | Prisma.ListEnumTipoAmbienteFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTipoAmbienteFilter<$PrismaModel> | $Enums.TipoAmbiente
}

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type EnumLocalizacaoWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Localizacao | Prisma.EnumLocalizacaoFieldRefInput<$PrismaModel>
  in?: $Enums.Localizacao[] | Prisma.ListEnumLocalizacaoFieldRefInput<$PrismaModel>
  notIn?: $Enums.Localizacao[] | Prisma.ListEnumLocalizacaoFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLocalizacaoWithAggregatesFilter<$PrismaModel> | $Enums.Localizacao
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLocalizacaoFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLocalizacaoFilter<$PrismaModel>
}

export type EnumTipoAmbienteWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TipoAmbiente | Prisma.EnumTipoAmbienteFieldRefInput<$PrismaModel>
  in?: $Enums.TipoAmbiente[] | Prisma.ListEnumTipoAmbienteFieldRefInput<$PrismaModel>
  notIn?: $Enums.TipoAmbiente[] | Prisma.ListEnumTipoAmbienteFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTipoAmbienteWithAggregatesFilter<$PrismaModel> | $Enums.TipoAmbiente
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTipoAmbienteFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTipoAmbienteFilter<$PrismaModel>
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type NestedDateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type NestedDateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type NestedEnumStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.Status | Prisma.EnumStatusFieldRefInput<$PrismaModel>
  in?: $Enums.Status[] | Prisma.ListEnumStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.Status[] | Prisma.ListEnumStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumStatusFilter<$PrismaModel> | $Enums.Status
}

export type NestedEnumTipoEmprestimoFilter<$PrismaModel = never> = {
  equals?: $Enums.TipoEmprestimo | Prisma.EnumTipoEmprestimoFieldRefInput<$PrismaModel>
  in?: $Enums.TipoEmprestimo[] | Prisma.ListEnumTipoEmprestimoFieldRefInput<$PrismaModel>
  notIn?: $Enums.TipoEmprestimo[] | Prisma.ListEnumTipoEmprestimoFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTipoEmprestimoFilter<$PrismaModel> | $Enums.TipoEmprestimo
}

export type NestedEnumStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Status | Prisma.EnumStatusFieldRefInput<$PrismaModel>
  in?: $Enums.Status[] | Prisma.ListEnumStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.Status[] | Prisma.ListEnumStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumStatusWithAggregatesFilter<$PrismaModel> | $Enums.Status
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumStatusFilter<$PrismaModel>
}

export type NestedEnumTipoEmprestimoWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TipoEmprestimo | Prisma.EnumTipoEmprestimoFieldRefInput<$PrismaModel>
  in?: $Enums.TipoEmprestimo[] | Prisma.ListEnumTipoEmprestimoFieldRefInput<$PrismaModel>
  notIn?: $Enums.TipoEmprestimo[] | Prisma.ListEnumTipoEmprestimoFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTipoEmprestimoWithAggregatesFilter<$PrismaModel> | $Enums.TipoEmprestimo
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTipoEmprestimoFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTipoEmprestimoFilter<$PrismaModel>
}

export type NestedEnumTipoChaveFilter<$PrismaModel = never> = {
  equals?: $Enums.TipoChave | Prisma.EnumTipoChaveFieldRefInput<$PrismaModel>
  in?: $Enums.TipoChave[] | Prisma.ListEnumTipoChaveFieldRefInput<$PrismaModel>
  notIn?: $Enums.TipoChave[] | Prisma.ListEnumTipoChaveFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTipoChaveFilter<$PrismaModel> | $Enums.TipoChave
}

export type NestedEnumTipoChaveWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TipoChave | Prisma.EnumTipoChaveFieldRefInput<$PrismaModel>
  in?: $Enums.TipoChave[] | Prisma.ListEnumTipoChaveFieldRefInput<$PrismaModel>
  notIn?: $Enums.TipoChave[] | Prisma.ListEnumTipoChaveFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTipoChaveWithAggregatesFilter<$PrismaModel> | $Enums.TipoChave
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTipoChaveFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTipoChaveFilter<$PrismaModel>
}

export type NestedEnumLocalizacaoFilter<$PrismaModel = never> = {
  equals?: $Enums.Localizacao | Prisma.EnumLocalizacaoFieldRefInput<$PrismaModel>
  in?: $Enums.Localizacao[] | Prisma.ListEnumLocalizacaoFieldRefInput<$PrismaModel>
  notIn?: $Enums.Localizacao[] | Prisma.ListEnumLocalizacaoFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLocalizacaoFilter<$PrismaModel> | $Enums.Localizacao
}

export type NestedEnumTipoAmbienteFilter<$PrismaModel = never> = {
  equals?: $Enums.TipoAmbiente | Prisma.EnumTipoAmbienteFieldRefInput<$PrismaModel>
  in?: $Enums.TipoAmbiente[] | Prisma.ListEnumTipoAmbienteFieldRefInput<$PrismaModel>
  notIn?: $Enums.TipoAmbiente[] | Prisma.ListEnumTipoAmbienteFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTipoAmbienteFilter<$PrismaModel> | $Enums.TipoAmbiente
}

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type NestedEnumLocalizacaoWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Localizacao | Prisma.EnumLocalizacaoFieldRefInput<$PrismaModel>
  in?: $Enums.Localizacao[] | Prisma.ListEnumLocalizacaoFieldRefInput<$PrismaModel>
  notIn?: $Enums.Localizacao[] | Prisma.ListEnumLocalizacaoFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLocalizacaoWithAggregatesFilter<$PrismaModel> | $Enums.Localizacao
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLocalizacaoFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLocalizacaoFilter<$PrismaModel>
}

export type NestedEnumTipoAmbienteWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TipoAmbiente | Prisma.EnumTipoAmbienteFieldRefInput<$PrismaModel>
  in?: $Enums.TipoAmbiente[] | Prisma.ListEnumTipoAmbienteFieldRefInput<$PrismaModel>
  notIn?: $Enums.TipoAmbiente[] | Prisma.ListEnumTipoAmbienteFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTipoAmbienteWithAggregatesFilter<$PrismaModel> | $Enums.TipoAmbiente
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTipoAmbienteFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTipoAmbienteFilter<$PrismaModel>
}


