
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const TipoEmprestimo = {
  ADMINISTRATIVO: 'ADMINISTRATIVO',
  NORMAL: 'NORMAL'
} as const

export type TipoEmprestimo = (typeof TipoEmprestimo)[keyof typeof TipoEmprestimo]


export const Status = {
  PENDENTE: 'PENDENTE',
  DEVOLVIDO: 'DEVOLVIDO'
} as const

export type Status = (typeof Status)[keyof typeof Status]


export const TipoChave = {
  ARMARIO: 'ARMARIO',
  AMBIENTE: 'AMBIENTE'
} as const

export type TipoChave = (typeof TipoChave)[keyof typeof TipoChave]


export const TipoAmbiente = {
  LABORATORIO: 'LABORATORIO',
  SALA_DE_AULA: 'SALA_DE_AULA',
  SALA_ADMINISTRATIVA: 'SALA_ADMINISTRATIVA',
  AUDITORIO: 'AUDITORIO'
} as const

export type TipoAmbiente = (typeof TipoAmbiente)[keyof typeof TipoAmbiente]


export const Localizacao = {
  SNO: 'SNO',
  VELHA: 'VELHA'
} as const

export type Localizacao = (typeof Localizacao)[keyof typeof Localizacao]
