
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"
export type * from '../models.js'
export type * from './prismaNamespace.js'
export const Decimal = runtime.Decimal
export const ModelName = {
  Operadores: 'Operadores',
  Session: 'Session',
  Account: 'Account',
  Usuarios: 'Usuarios',
  Verification: 'Verification',
  Emprestimo: 'Emprestimo',
  Chave: 'Chave',
  Chaves_Usuarios: 'Chaves_Usuarios',
  Ambiente: 'Ambiente',
  Armario: 'Armario'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/**
 * Enums
 */
export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const OperadoresScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  role: 'role'
} as const

export type OperadoresScalarFieldEnum = (typeof OperadoresScalarFieldEnum)[keyof typeof OperadoresScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  expiresAt: 'expiresAt',
  token: 'token',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  userId: 'userId'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const AccountScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  providerId: 'providerId',
  userId: 'userId',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  idToken: 'idToken',
  accessTokenExpiresAt: 'accessTokenExpiresAt',
  refreshTokenExpiresAt: 'refreshTokenExpiresAt',
  scope: 'scope',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AccountScalarFieldEnum = (typeof AccountScalarFieldEnum)[keyof typeof AccountScalarFieldEnum]


export const UsuariosScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  matricula: 'matricula'
} as const

export type UsuariosScalarFieldEnum = (typeof UsuariosScalarFieldEnum)[keyof typeof UsuariosScalarFieldEnum]


export const VerificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VerificationScalarFieldEnum = (typeof VerificationScalarFieldEnum)[keyof typeof VerificationScalarFieldEnum]


export const EmprestimoScalarFieldEnum = {
  id: 'id',
  chaveId: 'chaveId',
  usuarioSolicitanteId: 'usuarioSolicitanteId',
  usuarioDevolucaoId: 'usuarioDevolucaoId',
  operadorSolicitacaoId: 'operadorSolicitacaoId',
  operadorDevolucaoId: 'operadorDevolucaoId',
  dataRetirada: 'dataRetirada',
  dataRetorno: 'dataRetorno',
  status: 'status',
  tipo: 'tipo',
  justificativa: 'justificativa',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type EmprestimoScalarFieldEnum = (typeof EmprestimoScalarFieldEnum)[keyof typeof EmprestimoScalarFieldEnum]


export const ChaveScalarFieldEnum = {
  id: 'id',
  ambienteId: 'ambienteId',
  armarioId: 'armarioId',
  tipo: 'tipo'
} as const

export type ChaveScalarFieldEnum = (typeof ChaveScalarFieldEnum)[keyof typeof ChaveScalarFieldEnum]


export const Chaves_UsuariosScalarFieldEnum = {
  id: 'id',
  chaveId: 'chaveId',
  usuarioId: 'usuarioId'
} as const

export type Chaves_UsuariosScalarFieldEnum = (typeof Chaves_UsuariosScalarFieldEnum)[keyof typeof Chaves_UsuariosScalarFieldEnum]


export const AmbienteScalarFieldEnum = {
  id: 'id',
  codigo: 'codigo',
  nome: 'nome',
  capacidade: 'capacidade',
  localizacao: 'localizacao',
  tipo: 'tipo',
  precisaReserva: 'precisaReserva'
} as const

export type AmbienteScalarFieldEnum = (typeof AmbienteScalarFieldEnum)[keyof typeof AmbienteScalarFieldEnum]


export const ArmarioScalarFieldEnum = {
  id: 'id',
  codigo: 'codigo',
  localizacao: 'localizacao',
  bloco: 'bloco',
  andar: 'andar'
} as const

export type ArmarioScalarFieldEnum = (typeof ArmarioScalarFieldEnum)[keyof typeof ArmarioScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

